config/routes.rb
Rails.application.routes.draw do
  root "drills#index"

  draw :admin
  draw :api

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: "users/omniauth_callbacks",
  }

  devise_scope :user do
    get 'edit_profile', to: 'devise/registrations#edit_profile'
    get 'change_password', to: 'devise/registrations#change_password'
  end

  resources :drills do
    resources :problems, only: [:index], controller: "drills/problems"
  end

  # get 'edit_profile', to: 'users#edit_profile', as: "edit_profile"
  get 'mydrills', to: 'drills#mydrills'
  get 'solve/:id', to: 'drills#solve', as: "solve"

  resources :drill_likes, only: [:create, :destroy]

  resources :users, only: %i[show new create edit] do
    resources :solve
  end

  get "tos" => "static_pages#tos"
  get "policy" => "static_pages#policy"
end

app/models/drill.rb
class Drill < ApplicationRecord
  is_impressionable counter_cache: true
  enum state: { draft: 0, limited_open: 100, full_open: 200 }
  belongs_to :user
  has_many :problems
  has_many :drill_likes, dependent: :destroy

  validates :title, presence: true, length: { in: 1..32 }
  validates :user_id, presence: true, numericality: { only_integer: true, greater_than: 0 }, uniqueness: { scope: :title }
  validates :state, presence: true
end

app/controllers/api/drills_controller.rb
class API::DrillsController < API::ApplicationController
  def index
    @drills = Drill.order(created_at: "DESC").where(state: "full_open").page(params[:page]).per(10)
  end

  def new
    @drill = Drill.new
    @drill_user = current_user
    @problems = []
    @current_user_id = current_user.id
  end

  THRESHOLD_OF_PROBLEM_MASTERED = 2

  def show
    @current_user_id = current_user&.id
    @drill = Drill.find(params[:id])
    @drill_user = @drill.user.slice(:id, :login_name)
    order = params[:rand] ? "RANDOM()" : :id
    if current_user && params[:past]
      set_problems_when_past
    else
      @problems = @drill.problems.order(order).limit(params[:num])
      if current_user
        @problem_map = ProblemUserResult.where(
          user_id: current_user.id,
          problem_id: @problems.pluck(:id)
        ).to_h{ [_1.problem_id, _1] }
      end
    end
  end

  # - resultがあるもの
  #  - current_streak >= 2
  #  - current_streak < 2
  # - resultがないもの。
  private def set_problems_when_past
    order = params[:rand] ? "RANDOM()" : :id
    drill_problem_ids = @drill.problems.pluck(:id)
    mastered_ids = ProblemUserResult.where(
      user_id: current_user.id,
      problem_id: drill_problem_ids
    ).where("current_streak >= 2").pluck(:problem_id)
    ids = (Set[*drill_problem_ids] - Set[*mastered_ids]).to_a
    @problems = Problem.where(id: ids).order(order).limit(params[:num])
    @problem_map = ProblemUserResult.where(
      user_id: current_user.id,
      problem_id: @problems.map(&:id)
    ).to_h{ [_1.problem_id, _1] }
  end

  def grade
    grade_personal_result(current_user) if current_user
  end

  private def grade_personal_result(user)
    drill_id = params[:drill_id].to_i

    answer_paper = params[:answer_paper]
    problems = params[:problems]
    problems.each do |problem|
      problem_id = problem[:id]
      problem_user_result = ProblemUserResult.find_or_create_by(user: user, problem_id: problem_id)
      problem_user_result.number_of_submissions += 1
      if answer_paper[problem_id.to_s] == problem[:correct_option]
        problem_user_result.number_of_correct_answers += 1
        problem_user_result.current_streak += 1
      else
        problem_user_result.current_streak = 0
      end
      problem_user_result.save!
    end

    update_number_of_problem_mastered(drill_id)
  end

  private def update_number_of_problem_mastered(drill_id)
    return unless current_user

    drill_id = drill_id.id if drill_id.is_a?(Drill)
    number_of_problem_mastered = 0
    problem_ids = Drill.find(drill_id).problems.pluck(:id)
    ProblemUserResult.where(user: current_user, problem_id: problem_ids).each do |problem_result|
      if problem_result.current_streak >= THRESHOLD_OF_PROBLEM_MASTERED
        number_of_problem_mastered += 1
      end
    end
    drill_user_result = DrillUserResult.find_or_create_by(user: current_user, drill_id: drill_id)
    drill_user_result.number_of_problem_mastered = number_of_problem_mastered
    drill_user_result.save!
  end

  def mydrills
    drill_ids = DrillLike.where(user: current_user).pluck(:drill_id)
    @drills = Drill.find(drill_ids)
    @drill_user_result = DrillUserResult.where(drill: drill_ids, user: current_user).to_h{ [_1.drill_id, _1] }
  end
end

app/controllers/drills/problems_controller.rb
class Drills::ProblemsController < ApplicationController
  # drill_idから、多のproblemsを持ってくる。
  # problemsとcurernt_use.id でひっかかる ProblemUserResultsを持ってくる。
  def index
    drill = Drill.find(params[:drill_id])

    if current_user
      @problems = drill.problems.order(created_at: "ASC").includes(:problem_user_results)
      @problem_map = ProblemUserResult.where(
        user_id: current_user.id,
        problem_id: @problems.pluck(:id)
      ).to_h{ [_1.problem_id, _1] }
    else
      @problems = drill.problems.order(created_at: "ASC")
    end
  end
end

app/controllers/drills_controller.rb
class DrillsController < ApplicationController
  def index
    @drills = Drill.order(created_at: "DESC").page(params[:page]).where(state: :full_open).includes(:problems, :user)
  end

  def show
    @drill = Drill.find_by(id: params[:id])
    @drill.increment!(:number_of_views, 1)
    impressionist(@drill, nil, unique: [:session_hash])
    @problems = @drill.problems
    @problem_size = @problems.size

    if current_user
      @drill_user_result = DrillUserResult.find_by(user: current_user, drill: @drill)
      @number_of_problem_mastered = @drill_user_result&.number_of_problem_mastered
      @driill_is_mastered = true if @problem_size == @number_of_problem_mastered
    end
  end

  def new
    authenticate_user!
    redirect_to root_path unless current_user&.admin?
  end

  def create
    return unless current_user&.admin?

    drill = Drill.new(
      user: current_user,
      title: params[:drillTitle],
      guide: params[:drillGuide],
      state: :draft,
    )

    if drill.save
      json = {
        status: 200,
        message: "Success #{controller_name.capitalize} #{action_name.capitalize}",
        redirect_edit_url: "/drills/#{drill[:id]}/edit"
      }
      render status: 200, json: json
    else
      json = {
        status: 400,
        message: "Bad request #{controller_name.capitalize} #{action_name.capitalize}",
        redirect_edit_url: "/drills/new"
      }
      render status: 400, json: json
    end
  end

  def edit
    authenticate_user!
    @drill = Drill.find(params[:id])
    redirect_to root_path unless @drill.user == current_user || current_user&.admin?
  end

  def update
    return unless current_user&.admin?

    @drill = Drill.find_by(id: params[:id], user: current_user)
    @drill.title = params[:drillTitle]
    @drill.guide = params[:drillGuide]
    @drill.state = params[:drillState]
    @drill.save

    params[:problems].each do |problem_param|
      problem = Problem.find_or_create_by(id: problem_param[:id])
      problem.user ||= current_user
      problem.drill_id ||= @drill[:id]
      problem.title = problem_param[:title]
      problem.statement = problem_param[:statement]
      problem.format = "basic_choices"
      problem.choices = problem_param[:choices]
      problem.correct_option = 1
      problem.explanation = problem_param[:explanation] || ""
      problem.save!
    end
  end

  def solve
    render layout: 'logo_only'
  end

  def destroy
    drill = Drill.find(params[:id])
    if current_user == drill.user && drill.problems.size.zero?
      drill.destroy
    end
    redirect_to current_user
  end
end

app/views/drills/_form.html.erb
<div class="row">
  <div class="">
    <%= form_with(model: drill, local: true) do |f| %>

      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>

      <%= f.label :guide %>
      <%= f.text_area :guide, class: 'form-control' %>

      <%= f.submit "編集する", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/drills/_stamp.html.erb
<div class="stamp is-circle is-solved">
  <div class="stamp__content is-icon">習</div>
  <div class="stamp__content is-icon">得</div>
</div>

app/views/drills/edit.html.erb
<h1>ドリル編集画面</h1>

<br>
<div id="js-drill-edit">id="js-drill-edit"<div>
<br>

<%= link_to '詳細画面へ戻る', @drill %> |
<%= link_to 'ドリルの一覧へ', drills_path %>

app/views/drills/index.html.erb
<div class="drills-index-broad-frame">
  <h1 class="page-title">ドリル</h1>

  <% if current_user&.admin? %>
    <%= link_to 'ドリルを作成する', new_drill_path, class: "btn btn-primary w-100 fs-4 mb-3" %><br>
    <div><%= "ドリルがありません" if @drills.blank? %></div>
  <% end %>

  <div class="drills">
    <% @drills.each do |drill| %>
      <div class='index-drill'>
        <%= link_to drill, class: 'index-drill__inner' do %>

          <% if false %>
            <!-- stampベタ書き -->
            <div class="stamp is-circle is-solved is-sm">
              <div class="stamp__content is-icon">習</div>
              <div class="stamp__content is-icon">得</div>
            </div>
          <% end %>

          <div class="index-drill-title"><%= drill.title %></div>
          <div class="drill-guide"><%= drill.guide.truncate(100) %></div>

          <div class="problem-count">問題数<%= drill.problems.size %>問</div>
          <% if current_user&.admin? %>
            <div class="drill-user">
              <%= image_tag drill.user.icon_path, size: '32x32', alt: 'icon', class: 'a-user-icon' %>
              <div class="">
                <%= drill.user.login_name %>
              </div>
            </div>
            <div class="stats">
              <div class="stat">閲覧数: <%= drill.number_of_views %>回</div>
              <div class="stat">インプレッション: <%= drill.impressions_count %>回</div>
            </div>
          <% end %>
          <%= render 'drills/stamp' if false %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/drills/mydrills.html.erb
<h1>My Drills</h1>
<div id="js-mydrills"></div>

app/views/drills/new.html.erb
<h1>ドリル作成ページ</h1>

<div id="js-drill-form"></div>

app/views/drills/show.html.erb
<div class="drill-show-panel bg-light my-4 max-w768">
  <% if @driill_is_mastered %>
    <!-- stampベタ書き -->
    <div class="stamp is-circle is-solved">
      <div class="stamp__content is-icon">習</div>
      <div class="stamp__content is-icon">得</div>
    </div>
  <% end %>

  <div class="drill-show-top-panel">
    <div class="title-panel">
      <% if current_user %>
        <div class='like-button'>
          <% if DrillLike.exists?(user: current_user, drill: @drill) %>
            <%= form_with(model: current_user.drill_likes.find_by(drill_id: @drill.id), html: { method: :delete }, local: true) do |f| %>
              <%= f.submit "Unlike", class: "like-button__submit" %>
              <i class='fas fa-heart like-button__icon is-active'></i>
            <% end %>
          <% else %>
            <%= form_with(model: current_user.drill_likes.build, remote: true) do |f| %>
              <div><%= hidden_field_tag :drill_id, @drill.id %></div>
              <%= f.submit "Like", class: "like-button__submit" %>
              <i class='fas fa-heart like-button__icon is-inactive'></i>
            <% end %>
          <% end %>
        </div><!-- .like-button -->
      <% end %>
      <h1 class="drill-title"><%= @drill.title.presence || "無題" %></h1>
    </div>
    <div class="drill-guide my-4"><%= simple_format(h(@drill.guide.presence || "")) %></div>
  </div>
  <div class="drill-show-middle-panel">

    <div class="drill-problem-counts">
      <div class="text-ceneter">
        <div class="drill-stat-label text-center">全問題数</div>
        <div class="drill-stat-data text-center">
          <%= problems_count = @drill.problems.size %><span class="unit">問</span>
        </div>
      </div>
      <% if current_user %>
        <div class="text-ceneter">
          <div class="drill-stat-label text-center">習得問題数</div>
          <div class="drill-stat-data text-center">
            <%= @drill_user_result&.number_of_problem_mastered || '0' %><span class="unit">問</span>
          </div>
        </div>
        <div class="text-ceneter">
          <div class="drill-stat-label text-center">習得問題率</div>
          <div class="drill-stat-data text-center">
            <%= percent(@drill_user_result&.number_of_problem_mastered, @drill.problems.size) %><span class="unit">%</span>
          </div>
        </div>

      <% end %>
    </div>
  </div>

  <div class="drill-show-bottom-panel">
    <%= form_with url: "/solve/#{@drill.id}", method: "GET", class: "solve-drill-form" do |f| %>
      <div class="d-flex flex-row justify-content-around">
        <div class="form-check mt-3">
          <%= f.check_box :rand, {checked: true, class: "form-check-input"}, "true", nil %>
          <%= f.label :rand, "ランダムに出題する", class: "form-check-label" %>
        </div>

        <% if current_user && @drill_user_result && !@driill_is_mastered %>
          <div class="form-check mt-3">
            <%= f.check_box :past, {checked: true, class: "form-check-input"}, "true", nil %>
            <%= f.label :past, "未習得の問題に絞る", class: "form-check-label" %>
          </div>
        <% end %>

        <div class="flex-row mt-3">
          <label for="num">(最大)出題数</label>
          <%= f.select :num, options_for_select(problem_count_select_list(problems_count)), {}, class: "form-select-lg mb-3" %>
        </div>
      </div>

      <%= f.submit t("text.Solve_problems"), class: 'block-center w-75 btn btn-primary btn-lg mt-3' %>
    <% end %>
  </div>

  <% if current_user == @drill.user %>
    <hr>
    <div style="font-size: 8">
      <%= link_to "編集する", edit_drill_path(@drill) %>
    </div>
  <% elsif current_user&.admin? %>
    <hr>
    <div style="font-size: 8">
    <%= link_to "管理者編集", edit_drill_path(@drill) %>
    </div>
  <% end %>
  <% if current_user&.admin? %>
    <%= link_to "problems", drill_problems_path(@drill) %>
  <% end %>
</div>

<% if current_user&.admin? %>
  <%= image_tag @drill.user.icon_path, size: '56x56', alt: 'icon', class: 'a-user-icon' %>
  <div class="drill-use"><%= link_to @drill.user.login_name, @drill.user, class: "drill-user-name" %></div>
  <% if DrillLike.exists?(user: current_user, drill: @drill) %>
    <%= form_with(model: current_user.drill_likes.find_by(drill_id: @drill.id), html: { method: :delete }, local: true) do |f| %>
      <%= f.submit "Unlike", class: "btn btn-primary" %>
    <% end %>
  <% else %>
    <%= form_with(model: current_user.drill_likes.build, remote: true) do |f| %>
      <div><%= hidden_field_tag :drill_id, @drill.id %></div>
      <%= f.submit "Like", class: "btn btn-primary" %>
    <% end %>
  <% end %>
  <% if current_user == @drill.user && @drill.problems.size.zero? %>
    <%= link_to 'ドリル削除', "/drills/#{@drill.id}", method: :delete %>
  <% end %>
<% end %>

app/views/drills/solve.html.erb
<div id="js-solve"></div>

app/views/drills/solving.html.erb
<div id="js-solving"></div>