config/routes.rb
Rails.application.routes.draw do
  root "drills#index"

  draw :admin
  draw :api

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: "users/omniauth_callbacks",
  }

  devise_scope :user do
    get 'edit_profile', to: 'devise/registrations#edit_profile'
    get 'change_password', to: 'devise/registrations#change_password'
  end

  resources :drills do
    resources :problems, only: [:index], controller: "drills/problems"
  end

  # get 'edit_profile', to: 'users#edit_profile', as: "edit_profile"
  get 'mydrills', to: 'drills#mydrills'
  get 'solve/:id', to: 'drills#solve', as: "solve"

  resources :drill_likes, only: [:create, :destroy]

  resources :users, only: %i[show new create edit] do
    resources :solve
  end

  get "tos" => "static_pages#tos"
  get "policy" => "static_pages#policy"
end

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="footer-nav">
    <div class="footer-nav__items">
      <div class="footer-nav__item">
        <%= link_to t("word.privacy_policy"), policy_path, class: "footer-nav__link" %>
      </div>
      <div class="footer-nav__item">
        <%= link_to t("word.tos"), tos_path, class: "footer-nav__link" %>
      </div>
    </div>
  </div>
  <small class="footer-copyright">
    <span>©</span>
    <span>universato</span>
    <span>2021</span>
  </small>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-sm navbar-light bg-light transparent sticky-top">
  <div class="container-fluid">
    <a class="navbar-brand header__title" href="/drills">Brain Driller</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggler" aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarToggler">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      </ul>
      <ul class="navbar-nav d-flex no-wrap">
        <% if Rails.env.development? %>
          <% if current_user %>
          【開発】<%= current_user.email %>でログイン中
          <% end %>
        <% end %>
        <% if false %>
          <li class="nav-item"><%= link_to "トップ", root_path, class: "nav-link" %></li>
        <% end %>
        <% if user_signed_in? %>
          <li class="dropdown nav-item">
            <a href="#" class="dropdown-toggle nav-link fs-4" data-bs-toggle="dropdown">
              アカウント
            </a>
            <ul class="dropdown-menu">
              <% if current_user&.admin? %>
                <li class="nav-item"><%= link_to "プロフィール", user_path(current_user), class: "nav-link fs-4" %></li>
              <% end %>
              <li class="nav-item"><%= link_to "設定", edit_user_registration_path, class: "nav-link fs-4" %></li>
              <li class="nav-item">
                <%= link_to t("word.logout"), destroy_user_session_path, method: :delete, class: "nav-link fs-4" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to t("word.signup"), new_user_registration_path, class: "nav-link", tabindex: "-1", aria_disabled: "true" %>
          </li>
          <li class="nav-item">
            <%= link_to t("word.login"), new_user_session_path, class: "nav-link", tabindex: "-1", aria_disabled: "true" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_labo.html.erb
<% if false %>
  <i class="fa fa-clock-o"></i>
  <i class="fab fa-twitter"></i>
  <div id="js-hello"></div>
<% end %>
<%= debug(params) if Rails.env.development? && false %>

<% if Rails.env.development? && false %>
  <%= request.inspect %>
  <% r = request %>
  <%= {url: r.url, original_url: r.original_url, base_url: r.base_url, path: r.path, full_path: r.fullpath, path_info: r.path_info,  controller_class: r.controller_class, from: r.from, referer: r.referer,  request_method: r.request_method, uuid: r.uuid, negotiate: r.negotiate, headers: r.headers, flash: r.flash } %>
  <%= request.class %>
  <%= request.methods.sort.grep(/contro/) %>
<% end %>

app/views/layouts/_meta.html.erb
<meta name="keywords" content="クイズ,ドリル,学習">
<meta name="description" content="ドリルを作って解ける学習サイトです。">

<meta name="viewport" content="width=device-width,initial-scale=1">
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%# stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= stylesheet_pack_tag 'application' %>
<%= javascript_pack_tag 'application' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BrainDriller</title>
    <%= favicon_link_tag('favicon.png') %>
    <%= render 'layouts/meta' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <main>
      <div class="main-body">
        <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% end %>
        <%= yield %>
      </div>
    </main>
    <%= render 'layouts/labo' %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/layouts/logo_only.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BrainDriller</title>
    <%= render 'layouts/meta' %>
  </head>

  <body>
    <header>
      <div class="">
        <%= link_to 'BrainDriller', '/', class: 'navbar-brand header__title modest-logo-title' %>
      </div>
    </header>
    <main><%= yield %></main>
  </body>
</html>